version: "3"
services:

  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    env_file: .env  
    ports:
      - "0.0.0.0:8000:8000"
    command: bash -c  "python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    networks:
      - fmsb-network



  redis:
    # update he memory overcommit setting
    # 1/ sudo nano /etc/sysctl.conf
    # 2/ vm.overcommit_memory = 1
    # 3/ sudo sysctl -p
    container_name: redis
    image: redis
    user: redis
    command: redis-server /code/redis.conf
    restart: always
    volumes:
    - /code/redis.conf:/code/redis.conf
    - redis-data:/data
    - redis-logs:/var/log/redis
    networks:
      - fmsb-network

    

  celery:
    container_name: celery
    build: .
    env_file: .env
    command: celery -A config worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    restart: always
    networks:
      - fmsb-network



  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - fmsb-network

networks:
  default:
    driver: bridge
  fmsb-network:
    external: true

volumes:
  redis-data:
  redis-logs:
  db:
    driver: local


    